---
title: "Homework 2"
author: "Sarah Younes"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

As always, I will begin by loading the tidyverse.

```{r tidyverse, message = FALSE}
library(tidyverse)
```

# Problem 1

First, I will clean the data in pols-month.csv.

```{r pols_month_df}
pols_month_df =
  read.csv("Data/pols-month.csv") |>
  separate(mon, into = c("year", "month", "day"), sep = "-") |>
  mutate(
     month = replace(month, month == "01", "Jan"),
     month = replace(month, month == "02", "Feb"),
     month = replace(month, month == "03", "Mar"),
     month = replace(month, month == "04", "Apr"),
     month = replace(month, month == "05", "May"),
     month = replace(month, month == "06", "Jun"),
     month = replace(month, month == "07", "Jul"),
     month = replace(month, month == "08", "Aug"),
     month = replace(month, month == "09", "Sep"),
     month = replace(month, month == "10", "Oct"),
     month = replace(month, month == "11", "Nov"),
     month = replace(month, month == "12", "Dec")
  ) |>
  mutate(
    president = prez_gop) |>
  mutate(
    president = replace(president, president == "1", "Republican"),
    president = replace(president, president == "0", "Democrat")
  ) |>
  select(year, month, president, gov_gop, sen_gop, rep_gop, gov_dem, sen_dem, rep_dem)
```
    
Second, I will clean the data in snp.csv.

```{r}
snp_df =
  read.csv("Data/snp.csv") |>
  separate(date, into = c("month", "day", "year"), sep = "/") |>
  mutate(
     month = replace(month, month == "1", "Jan"),
     month = replace(month, month == "2", "Feb"),
     month = replace(month, month == "3", "Mar"),
     month = replace(month, month == "4", "Apr"),
     month = replace(month, month == "5", "May"),
     month = replace(month, month == "6", "Jun"),
     month = replace(month, month == "7", "Jul"),
     month = replace(month, month == "8", "Aug"),
     month = replace(month, month == "9", "Sep"),
     month = replace(month, month == "10", "Oct"),
     month = replace(month, month == "11", "Nov"),
     month = replace(month, month == "12", "Dec")
  ) |>
  select(year, month, close)
```
    
Third, I will tidy the data in unemployment.csv.

```{r}
unemployment_df =
  read.csv("Data/unemployment.csv") |>
  janitor::clean_names() |>
  pivot_longer(
    jan:dec,
    names_to = "month",
    values_to = "unemployment"
  ) |>
  mutate(month = str_to_title(month))
```

Now, I will join the three datasets into a single data frame.

# Problem 2

# Problem 3